const carBrands: { [key: string]: string[] } = {
  Tesla: [
    'Cybertruck',
    'Model 3',
    'Model S',
    'Model X',
    'Model Y',
    'Roadster G1',
    'Roadster G2',
    'Roadster IM',
    'Semi',
    'Model XXL',
  ],
  Ford: ['Mustang', 'Escape', 'Fusion', 'Explorer', 'Mondeo', 'Fiesta', 'Focus', 'S-MAX', 'Galaxy', 'Escort'],
  Mercedes: ['AMG GT', '170S', 'R129', 'C111', '300 SLR', 'L206', 'Vaneo', 'W111', 'AMG ONE', 'R172'],
  BMW: ['E30', 'E34', 'E92', 'F01', 'G15', 'GINA', 'Hydrogen 7', 'i3', 'X5', 'Z8'],
  Nissan: ['Bassara', 'Caball', 'Cima', 'Cube', 'Navara', 'Cherry', 'Pathfinder', 'Pivo', 'Terrano', 'X-Trail'],
  Audi: ['A4', 'A7', 'A8', 'Q7', 'Q8', 'SQ2', 'RS 3', 'TT RS', 'RS 2 Avant', 'TTS'],
  Porsche: [
    '64',
    '356',
    '360 Cisitalia',
    '597 Jagdwagen',
    '904',
    '911',
    '928',
    'Boxster',
    'Carrera',
    'Cayenne',
    'Cayman',
  ],
  Ferrari: [
    '550 Maranello',
    '599 GTB Fiorano',
    'America',
    '250 GTO',
    'Berlinetta Boxer',
    'Daytona',
    'Dino',
    'Enzo',
    '612 Scaglietti',
    'Testarossa',
  ],
  Lamborghini: [
    'Miura',
    'Espada',
    'Islero',
    'Jarama',
    'Urraco',
    'Countach',
    'Silhouette',
    'Jalpa',
    'Diablo',
    'Murciélago',
    'Gallardo',
    'Reventón',
    'Aventador',
    'Sesto Elementо',
    'Veneno',
    'Huracán',
    'Centenario',
  ],
  Bugatti: [
    'Bolide',
    'Divo',
    'Type 13',
    'Chiron',
    'EB110',
    '16C Galibier',
    'Mistral',
    'Type 35',
    'Type 41 Royale',
    'Veyron',
  ],
};

export default carBrands;
