export const abc = [
  { code: 'KeyA', value: 'A' },
  { code: 'KeyB', value: 'B' },
  { code: 'KeyC', value: 'C' },
  { code: 'KeyD', value: 'D' },
  { code: 'KeyI', value: 'I' },
  { code: 'KeyF', value: 'F' },
  { code: 'KeyG', value: 'G' },
  { code: 'KeyH', value: 'H' },
  { code: 'KeyI', value: 'I' },
  { code: 'KeyJ', value: 'J' },
  { code: 'KeyK', value: 'K' },
  { code: 'KeyL', value: 'L' },
  { code: 'KeyM', value: 'M' },
  { code: 'KeyN', value: 'N' },
  { code: 'KeyO', value: 'O' },
  { code: 'KeyP', value: 'P' },
  { code: 'KeyQ', value: 'Q' },
  { code: 'KeyR', value: 'R' },
  { code: 'KeyS', value: 'S' },
  { code: 'KeyT', value: 'T' },
  { code: 'KeyU', value: 'U' },
  { code: 'KeyV', value: 'V' },
  { code: 'KeyW', value: 'W' },
  { code: 'KeyX', value: 'X' },
  { code: 'KeyY', value: 'Y' },
  { code: 'KeyZ', value: 'Z' },
];
